{"uuid": "60097875-12a2-41b8-a445-d5dd9b6b404f", "children": ["e20964f5-df9b-4c4e-b58e-e48b56a4c2b5", "ad021d1b-57d0-42d6-b438-118a7fe1c638", "42bb9573-af61-4246-8436-7a797d2d914a", "446c628e-f5aa-4edb-9f0f-9a64ae639bbf", "63fd1add-38fe-40e5-ad67-f0a700cfcf83", "19fc2d8f-92ef-4961-8897-18cf61ee65cf", "f9dfc385-72f4-40fb-9c87-c313402721d7", "35065177-be2c-48c5-9ffa-7053f1bcbaeb"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "OSError: [Errno 22] Invalid argument: 'F:\\\\python\\\\zrapiautotestv1.0/TestData/token.yaml'\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\python.py\", line 703, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func(arg)\n  File \"F:\\python\\zrapiautotestv1.0\\TestCase\\StockQuotation\\AstockRelevance\\test_Astock_F10briefing.py\", line 13, in setup_class\n    login()\n  File \"F:\\python\\zrapiautotestv1.0\\Common\\login.py\", line 19, in login\n    with open(glo.BASE_DIR + r'/TestData/token.yaml', 'w') as file:\n"}, "start": 1594176784425, "stop": 1594176784447}], "start": 1594176784425, "stop": 1594176784574}